version: '3.3'
services:
  nginx: 
    #image: nginx:1.25
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    hostname: nginx
    restart: always
    env_file:
      - ./.env
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}
    volumes:
    #  - ./.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./views/index.ejs:/usr/share/nginx/html/index.ejs
    depends_on:
      - nodejs
     
  nodejs:
    build: 
      context: .
      dockerfile: nodejs.dockerfile
    container_name: nodejs
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
    #ports:
    #  - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - mongodb
    #links:
     # - mongodb
  
  mongodb:
    image: mongo:6.0.2
    restart: always
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./.env
#    ports:
#      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    environment:
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_DB=${MONGODB_DATABASE}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodb:/data/db

volumes:
  mongodb:
