version: '3.8'
services:
  nodejs:
    build: 
      context: .
      dockerfile: nodejs.dockerfile
    container_name: nodejs
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongodb
    links:
      - mongodb
  
  mongodb:
    image: mongo:6.0
    restart: always
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      - NODE_PORT=$NODE_LOCAL_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - ./fruits.js:/docker-entrypoint-initdb.d/fruits.js:ro
      - mongodb:/data/db

volumes:
  mongodb: