version: '3.8'
services:
  nodejs:
    build: 
      context: .
      dockerfile: nodejs.dockerfile
    container_name: nodejs
    ports:
      - 8080:8080
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    hostname: mongodb
    