version: '3.3'
services:
  nodejs:
    build: 
      context: .
      dockerfile: nodejs.dockerfile
    container_name: nodejs
    restart: always
    env_file:
      - ./.env
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - mongodb
    #links:
     # - mongodb
  
  mongodb:
    image: mongo:6.0.2
    restart: always
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./.env
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    environment:
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_DB=${MONGODB_DATABASE}
      #- MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      #- MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./fruits.js:/docker-entrypoint-initdb.d/fruits.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
