version: '3.3'
services:
  nginx: 
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    hostname: nginx
    restart: always
    env_file:
      - ./.env
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}
    depends_on:
      - nodejs
    networks:
      - frontend
     
  nodejs:
    build: 
      context: .
      dockerfile: nodejs.dockerfile
    container_name: nodejs
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  
  mongodb:
    image: mongo:6.0.2
    restart: always
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./.env
    environment:
      - MONGO_USERNAME=${MONGODB_USER}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_DB=${MONGODB_DATABASE}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodb:/data/db
    networks:
      - backend

volumes:
  mongodb:
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
